table feature_importance
	lineageTag: 81e54473-b97d-4d48-8952-38f71c4b4190

	column feature
		dataType: string
		lineageTag: 108516bc-6d85-486b-9617-0c9d705fc8ef
		summarizeBy: none
		sourceColumn: feature

	column mean_abs_shap
		dataType: double
		formatString: 0.000
		lineageTag: b66f8b41-ab2d-42cf-9845-d139f557a9a6
		summarizeBy: sum
		sourceColumn: mean_abs_shap

	column feature_label
		dataType: string
		lineageTag: 557322b0-1032-4923-9bfe-1b1c7a4ef01e
		summarizeBy: none
		sourceColumn: feature_label

	column feature_label_es
		dataType: string
		lineageTag: c786b372-e5fb-4c60-8baa-9b4216267db7
		summarizeBy: none
		sourceColumn: feature_label_es

	partition feature_importance = m
		mode: import
		source =
				let
					Source = PostgreSQL.Database("localhost:5433", "retail"),
					Data = Source{[Schema = "public", Item = "feature_importance"]}[Data],
					// Same names the Action list uses, so the business reads one vocabulary
					Labels = [
						recency_days = "Days since last order",
						frequency = "Orders",
						monetary = "Total spend",
						avg_order_value = "Avg order value",
						tenure_days = "Days as customer",
						distinct_products = "Distinct products",
						orders_last_90d = "Orders last 90 days",
						cancel_rate = "Cancellation rate",
						is_uk = "Based in the UK"
					],
					WithLabel = Table.AddColumn(Data, "feature_label", each Record.FieldOrDefault(Labels, [feature], [feature]), type text),
					// Spanish labels for the Spanish report (ChurnDashboardES)
					LabelsEs = [
						recency_days = "Días sin comprar",
						frequency = "Pedidos",
						monetary = "Gasto total",
						avg_order_value = "Ticket promedio",
						tenure_days = "Días como cliente",
						distinct_products = "Productos distintos",
						orders_last_90d = "Pedidos 90 días",
						cancel_rate = "Tasa de cancelación",
						is_uk = "Está en Reino Unido"
					],
					WithLabelEs = Table.AddColumn(WithLabel, "feature_label_es", each Record.FieldOrDefault(LabelsEs, [feature], [feature]), type text)
				in
					WithLabelEs

