table model_metrics
	lineageTag: d497cb7c-692a-4602-b19d-8b7fe26fcd11

	measure 'Selected test ROC-AUC' = CALCULATE(SUM(model_metrics[value]), model_metrics[metric] = "Test ROC-AUC", model_metrics[is_selected] = 1)
		formatString: 0.000
		lineageTag: edf98ec6-f3a8-4833-b7eb-d3756893f71b

	measure 'Selected recall' = CALCULATE(SUM(model_metrics[value]), model_metrics[metric] = "Recall", model_metrics[is_selected] = 1)
		formatString: 0.0%
		lineageTag: 81e38bfb-e48a-49ec-b3fb-5077e2fd5251

	measure 'Selected precision' = CALCULATE(SUM(model_metrics[value]), model_metrics[metric] = "Precision", model_metrics[is_selected] = 1)
		formatString: 0.0%
		lineageTag: 2f36c61e-0417-48ee-a0c6-2b7330226ff5

	measure 'CV ROC-AUC gain over baseline' = CALCULATE(SUM(model_metrics[value]), model_metrics[metric] = "CV ROC-AUC", model_metrics[is_selected] = 1) - CALCULATE(SUM(model_metrics[value]), model_metrics[metric] = "CV ROC-AUC", model_metrics[is_selected] = 0)
		formatString: +0.000;-0.000
		lineageTag: e5f6cb82-44d8-4c67-a6a6-7c86d15ad250

	column model
		dataType: string
		lineageTag: 854e0679-c520-4004-acc0-66c4702f72ef
		summarizeBy: none
		sourceColumn: model

	column metric
		dataType: string
		lineageTag: e40486de-01c8-4737-a20d-26f59cf7d1cb
		summarizeBy: none
		sourceColumn: metric
		sortByColumn: metric_order

	column metric_order
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 47007897-d73b-4231-bf45-149d83b0a7da
		summarizeBy: none
		sourceColumn: metric_order

	column value
		dataType: double
		formatString: 0.000
		lineageTag: 83e78377-656c-477c-aa28-4712fa35d53f
		summarizeBy: sum
		sourceColumn: value

	column is_selected
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 340698d0-f631-496a-826d-4b1a2deea835
		summarizeBy: none
		sourceColumn: is_selected

	column model_es
		dataType: string
		lineageTag: 6d2dc3b3-a90c-47cf-97cf-73efb6c5c8cf
		summarizeBy: none
		sourceColumn: model_es

	column metric_es
		dataType: string
		lineageTag: 641726f2-7359-4de0-b9c0-8a0018d2ffdf
		summarizeBy: none
		sourceColumn: metric_es
		sortByColumn: metric_order

	partition model_metrics = m
		mode: import
		source =
				let
					Source = PostgreSQL.Database("localhost:5433", "retail"),
					Data = Source{[Schema = "public", Item = "model_metrics"]}[Data],
					// Spanish labels for the Spanish report (ChurnDashboardES)
					ModelEs = [#"Logistic regression" = "Regresión logística", XGBoost = "XGBoost"],
					MetricEs = [
						#"CV ROC-AUC" = "ROC-AUC (CV)",
						#"Test ROC-AUC" = "ROC-AUC (prueba)",
						#"Test PR-AUC" = "PR-AUC (prueba)",
						Precision = "Precisión",
						Recall = "Recall",
						F1 = "F1"
					],
					WithModelEs = Table.AddColumn(Data, "model_es", each Record.FieldOrDefault(ModelEs, [model], [model]), type text),
					WithMetricEs = Table.AddColumn(WithModelEs, "metric_es", each Record.FieldOrDefault(MetricEs, [metric], [metric]), type text)
				in
					WithMetricEs

